import hashlib
import hmac
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Callable

import jwt
import yaml
from pwdlib import PasswordHash
from pwdlib.hashers.argon2 import Argon2Hasher

from .config import AuthSettings


DEFAULT_HASHER_CONFIG = {
    "time_cost": 3,
    "memory_cost": 65536,
    "parallelism": 4,
    "hash_len": 32,
    "salt_len": 16,
}


def _load_hasher_config(path: str | Path = "./hasher-config.yaml") -> dict:
    """Load argon2id tuning parameters from a YAML file.

    Args:
        path: Path to a YAML file with keys `time_cost`, `memory_cost`,
            `parallelism`, `hash_len`, `salt_len`.

    Returns:
        Parsed dict ready to splat into `Argon2Hasher(...)`.

    Raises:
        FileNotFoundError: If `path` does not exist.
        yaml.YAMLError: If the file is not valid YAML.
    """
    with open(path, "r") as f:
        return yaml.safe_load(f)


def _peppered(password: str, pepper: bytes) -> str:
    """Pre-hash a password with the deployment pepper using HMAC-SHA256.

    HMAC-SHA256(pepper, password) -> hex digest. Both `hash` and `verify`
    paths must apply this identically; the argon2id input is always the
    64-char hex digest, never the raw password.

    Args:
        password: Plaintext password as supplied by the user.
        pepper: Deployment-wide secret key (env-only, never on disk).

    Returns:
        64-character lowercase hex digest. Fixed length regardless of
        original password length.
    """
    return hmac.new(pepper, password.encode("utf-8"), hashlib.sha256).hexdigest()


@dataclass
class PasswordHasher:
    """Argon2id hasher with deployment-wide pepper applied via HMAC pre-hash.

    * Salt is per-password and generated by argon2id; it lives inside the
      returned PHC string.
    * Pepper is env-only; HMAC-SHA256(pepper, password) feeds argon2id, so
      the pepper itself never reaches the database.

    Attributes:
        hash: `(plaintext) -> argon2id PHC string`. Use at registration.
        verify: `(plaintext, stored_hash) -> bool`. Use at login.
        dummy_verify: `() -> None`. Call on unknown-user paths to keep
            response timing constant and block username enumeration.
    """

    hash: Callable[[str], str]
    verify: Callable[[str, str], bool]
    dummy_verify: Callable[[], None]


def make_password_hasher(
    settings: AuthSettings,
    hasher_config_path: str | Path | None = None,
) -> PasswordHasher:
    """Build a `PasswordHasher` bound to the deployment pepper.

    The returned object closes over the pepper (read from
    `settings.pepper_secret`) and a configured `Argon2Hasher`. Cheap to
    keep as a process-wide singleton; do not rebuild per request.

    Args:
        settings: Loaded `AuthSettings`. Provides `pepper_secret`.
        hasher_config_path: Optional path to a YAML file overriding the
            default argon2id parameters. If `None`, uses
            `DEFAULT_HASHER_CONFIG`.

    Returns:
        A `PasswordHasher` whose `.hash` / `.verify` / `.dummy_verify`
        callables are pepper- and argon2-bound.
    """
    cfg = (
        DEFAULT_HASHER_CONFIG
        if hasher_config_path is None
        else _load_hasher_config(hasher_config_path)
    )
    pepper = settings.pepper_secret.get_secret_value().encode("utf-8")

    pwd = PasswordHash([
        Argon2Hasher(
            time_cost=cfg["time_cost"],
            memory_cost=cfg["memory_cost"],
            parallelism=cfg["parallelism"],
            hash_len=cfg["hash_len"],
            salt_len=cfg["salt_len"],
        )
    ])
    dummy_hash = pwd.hash(_peppered("dummy-password-123", pepper))

    def hash_password(password: str) -> str:
        """Hash a plaintext password for storage.

        Args:
            password: User-supplied plaintext.

        Returns:
            Argon2id PHC string suitable for direct storage in the user
            record (e.g. `auth.password_hash`).
        """
        return pwd.hash(_peppered(password, pepper))

    def verify_password(plain_password: str, hashed_password: str) -> bool:
        """Verify a plaintext password against a stored argon2id hash.

        Args:
            plain_password: User-supplied plaintext from the login request.
            hashed_password: Argon2id PHC string previously produced by
                `hash_password`.

        Returns:
            `True` iff the password matches.
        """
        return pwd.verify(_peppered(plain_password, pepper), hashed_password)

    def dummy_verify() -> None:
        """Perform a fake hash check against a pre-baked dummy hash.

        Used on unknown-user paths so that wrong-username and wrong-
        password requests take equivalent time, preventing username
        enumeration via response-time side channels.
        """
        pwd.verify(_peppered("dummy", pepper), dummy_hash)

    return PasswordHasher(
        hash=hash_password,
        verify=verify_password,
        dummy_verify=dummy_verify,
    )


def create_access_token(
    settings: AuthSettings,
    identity: str,
    roles: list[str],
    extra: dict | None = None,
) -> str:
    """Mint a short-lived JWT access token.

    Payload contains `sub`, `roles`, `type="access"`, `exp`, plus any keys
    from `extra`. Signed with `settings.jwt_secret_key` using
    `settings.jwt_algorithm`. Lifetime: `settings.access_ttl_minutes`.

    Args:
        settings: Loaded `AuthSettings`.
        identity: Stable user identifier — goes into `sub`.
        roles: Roles to embed for use by `require_roles(...)`.
        extra: Optional additional claims to merge into the payload
            (e.g. `{"account_type": "influencer", "uid": "..."}`).

    Returns:
        Encoded JWT string.
    """
    payload = {
        "sub": identity,
        "roles": roles,
        "type": "access",
        "exp": datetime.now(timezone.utc) + timedelta(minutes=settings.access_ttl_minutes),
        **(extra or {}),
    }
    return jwt.encode(
        payload,
        settings.jwt_secret_key.get_secret_value(),
        algorithm=settings.jwt_algorithm,
    )


def create_refresh_token(
    settings: AuthSettings,
    identity: str,
    roles: list[str],
) -> str:
    """Mint a long-lived JWT refresh token.

    Payload contains `sub`, `roles`, `type="refresh"`, `exp`. Same
    signing key and algorithm as access tokens; the `type` field is
    what distinguishes them. Lifetime: `settings.refresh_ttl_minutes`.

    Args:
        settings: Loaded `AuthSettings`.
        identity: Stable user identifier — goes into `sub`.
        roles: Roles to embed.

    Returns:
        Encoded JWT string suitable for the `refresh_token` cookie.
    """
    payload = {
        "sub": identity,
        "roles": roles,
        "type": "refresh",
        "exp": datetime.now(timezone.utc) + timedelta(minutes=settings.refresh_ttl_minutes),
    }
    return jwt.encode(
        payload,
        settings.jwt_secret_key.get_secret_value(),
        algorithm=settings.jwt_algorithm,
    )


def decode_token(settings: AuthSettings, token: str) -> dict:
    """Decode and validate a JWT, returning its payload.

    Validates signature and expiry. Does NOT check the `type` field —
    callers must inspect `payload["type"]` themselves to distinguish
    access vs. refresh.

    Args:
        settings: Loaded `AuthSettings`.
        token: Encoded JWT string.

    Returns:
        Decoded payload dict.

    Raises:
        jwt.ExpiredSignatureError: Token `exp` is in the past.
        jwt.InvalidTokenError: Signature mismatch or malformed token.
    """
    return jwt.decode(
        token,
        settings.jwt_secret_key.get_secret_value(),
        algorithms=[settings.jwt_algorithm],
    )
